const ENV={
desk:{name:'Prima Desk',sub:'Ambiente Comune',hero:'desk',primary:'+ Nuovo ordinativo',views:[
['desk-home','D01','Scrivania'],['desk-new','D02','Nuovo ordinativo'],['desk-orders','D03','Ordinativi'],['desk-docs','D04','Documenti'],['desk-opps','D05','Bollettini'],['desk-training','D06','Formazione']]},
workbench:{name:'Prima Workbench',sub:'Ambiente professionisti',hero:'workbench',primary:'Prendi in carico',views:[
['wb-home','W01','Coda lavoro'],['wb-case','W02','Pratica PI-021'],['wb-sources','W03','Fonti & versioni'],['wb-validate','W04','Validazione'],['wb-delivery','W05','Consegne']]},
control:{name:'Prima Control',sub:'Amministrazione e governo',hero:'control',primary:'Esporta audit',views:[
['ctl-home','C01','Quadro di controllo'],['ctl-contracts','C02','Contratti & plafond'],['ctl-users','C03','Utenti & ruoli'],['ctl-sla','C04','SLA & qualità'],['ctl-audit','C05','Audit & sicurezza'],['ctl-config','C06','Configurazione']]},
patrimonio:{name:'Patrimonio & Progetti',sub:'Asset e opportunità territoriali',hero:'patrimonio',primary:'+ Nuovo asset',views:[
['pat-home','P01','Portfolio'],['pat-map','P02','Mappa'],['pat-asset','P03','Asset'],['pat-demand','P04','Domanda / Fabbisogni'],['pat-match','P05','Opportunity Match'],['pat-dossier','P06','Opportunity dossier'],['pat-network','P07','Progetti in rete'],['pat-quality','P08','Data quality'],['pat-admin','P09','Admin / Ruoli'],['pat-integrations','P10','Integrazioni']]}
};
let currentEnv='desk',currentView='desk-home',guideIndex=0,demoStep=0,modalCallback=null;
const q=s=>document.querySelector(s),qa=s=>document.querySelectorAll(s);
function goHome(){q('#ecosystem').classList.add('hidden');q('#home').classList.remove('hidden');closeGuide();window.scrollTo(0,0)}
function enterEnv(env,view){currentEnv=env;const e=ENV[env];currentView=view||e.views[0][0];q('#home').classList.add('hidden');q('#ecosystem').classList.remove('hidden');q('#envSelect').value=env;q('#envName').textContent=e.name;q('#envSub').textContent=e.sub;q('#primaryAction').textContent=e.primary;q('#primaryAction').onclick=()=>primaryAction(env);renderNav();renderView();closeGuide();window.scrollTo(0,0)}
function renderNav(){const e=ENV[currentEnv];q('#nav').innerHTML=e.views.map(([id,code,label])=>`<button class="${id===currentView?'active':''}" onclick="showView('${id}')"><small>${code}</small>${label}</button>`).join('')}
function showView(id){currentView=id;renderNav();renderView();closeGuide();window.scrollTo({top:0,behavior:'smooth'})}
function title(){const v=ENV[currentEnv].views.find(x=>x[0]===currentView);return v?`${v[1]} · ${v[2]}`:''}
function renderView(){q('#crumb').textContent=title();q('#content').innerHTML=templates[currentView]();bindLocal()}
function bindLocal(){qa('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));}
function primaryAction(env){if(env==='desk')showView('desk-new');else if(env==='workbench')toast('Pratica PI-021 presa in carico (simulazione)');else if(env==='control')toast('Audit esportato (simulazione)');else openAssetModal()}
function hero(title,text){return `<div class="hero ${ENV[currentEnv].hero}" data-guide="hero"><h1>${title}</h1><p>${text}</p></div>`}
function kpis(items){return `<div class="grid kpis" data-guide="kpis">${items.map(i=>`<div class="card kpi"><div class="label">${i[0]}</div><div class="value">${i[1]}</div><div class="note">${i[2]||''}</div></div>`).join('')}</div>`}
function status(t,c='ok'){return `<span class="pill ${c}">${t}</span>`}
function cardTable(head,rows){return `<div class="card"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
const templates={
'desk-home':()=>hero('Scrivania del Comune','Il referente vede richieste, scadenze e consegne. La pratica PI-021 è la stessa che i professionisti lavorano nel Workbench e che Control traccia nel contratto.')+
kpis([['Pratiche aperte','3','1 prioritaria'],['Plafond annuo','€ 7.350','su € 12.000'],['Consegne da leggere','2','ultima oggi'],['Bollettini nuovi','1','finanziamenti']])+
`<div class="grid two"><div class="card" data-guide="case"><div class="section-title"><h2>Pratica prioritaria · PI-021</h2>${status('In validazione','warn')}</div><h3>Schema di determinazione — manutenzione straordinaria</h3><p class="mini">Ordinativo O6 · valore €450 · termine 5 giorni lavorativi</p><div class="timeline"><div class="step done">Richiesta</div><div class="step done">Presa in carico</div><div class="step done">Elaborazione</div><div class="step current">Validazione</div><div class="step">Accettazione</div><div class="step">Chiusura</div></div><div class="decision" style="margin-top:14px"><button class="btn primary" onclick="showView('desk-orders')">Apri pratica</button><button class="btn" onclick="showView('desk-docs')">Documenti</button></div></div><div class="card" data-guide="next"><h2>Prossime azioni</h2><div class="list"><div class="list-item"><div><b>PI-021</b><div class="mini">Attendere versione validata</div></div>${status('oggi','blue')}</div><div class="list-item"><div><b>PI-023</b><div class="mini">Integrare allegato tecnico</div></div>${status('da fare','warn')}</div><div class="list-item"><div><b>Plafond</b><div class="mini">61% utilizzato</div></div>${status('regolare','ok')}</div></div></div></div>`,
'desk-new':()=>hero('Nuovo ordinativo','La richiesta è guidata: campi necessari, tariffa e gate sono visibili prima dell’invio.')+
`<div class="card" data-guide="form"><div class="form-grid"><div class="field"><label>Oggetto</label><input value="Schema di determinazione — manutenzione straordinaria"></div><div class="field"><label>Prestazione</label><select><option>O6 · Bozza di determinazione / deliberazione</option><option>O2 · Parere base</option><option>O3 · Parere medio</option></select></div><div class="field"><label>Termine</label><select><option>Ordinario · 5 giorni lavorativi</option><option>Urgenza motivata</option></select></div><div class="field"><label>Referente Ente</label><input value="Maria Bianchi"></div><div class="field"><label>Risultato richiesto</label><textarea>Bozza completa con riferimenti normativi e campi da completare a cura dell'Ente.</textarea></div><div class="field"><label>Documenti allegati</label><textarea>Capitolato; preventivo; CUP; quadro economico.</textarea></div></div><div class="alert" style="margin-top:14px">Prima dell'invio il sistema verifica capienza, referente, classificazione e regole documentali.</div><div class="decision" style="margin-top:14px"><button class="btn primary" onclick="toast('Ordinativo creato: simulazione')">Invia ordinativo</button><button class="btn">Salva bozza</button></div></div>`,
'desk-orders':()=>hero('Ordinativi e stato','L’Ente consulta ciò che ha richiesto senza entrare negli strumenti interni di lavorazione di PRIMA.')+
cardTable(['Codice','Prestazione','Valore','Stato','Azione'],[
['PI-021','O6 · Bozza determinazione','€450',status('Validazione','warn'),'<button class="btn" onclick="openCaseModal()">Dettaglio</button>'],
['PI-023','O3 · Parere complessità media','€450',status('Integrazione richiesta','blue'),'<button class="btn">Apri</button>'],
['PI-024','O1 · Quesito rapido','€100',status('Consegnato','ok'),'<button class="btn">Apri</button>']]),
'desk-docs':()=>hero('Documenti','Versioni e consegne sono collegate alle pratiche. Il prototipo distingue ciò che il Comune ha inviato da ciò che PRIMA ha elaborato.')+
cardTable(['Documento','Pratica','Versione','Stato','Azione'],[
['Capitolato manutenzione.pdf','PI-021','Ente · 01',status('Acquisito','ok'),'<button class="btn">Anteprima</button>'],
['Bozza determinazione.docx','PI-021','PRIMA · v2',status('In validazione','warn'),'<button class="btn">Dettaglio</button>'],
['Nota integrativa.pdf','PI-023','Ente · 02',status('Nuovo','blue'),'<button class="btn">Apri</button>']]),
'desk-opps':()=>hero('Bollettini opportunità','Segnalazioni periodiche basate su fonti ufficiali. Non sostituiscono una valutazione di ammissibilità o convenienza.')+
cardTable(['Bollettino','Periodo','Schede','Pubblicato','Azione'],[['N. 07/2026','16–30 settembre','12','30/09/2026','<button class="btn" data-toast="PDF bollettino: simulazione">Scarica</button>'],['N. 06/2026','1–15 settembre','9','15/09/2026','<button class="btn">Scarica</button>']]),
'desk-training':()=>hero('Formazione operativa','Materiali essenziali per comprendere procedure, strumenti e responsabilità senza trasformare la piattaforma in un corso generalista.')+`<div class="grid three"><div class="card"><h3>Ordinativi</h3><p class="mini">Come classificare la richiesta e allegare le evidenze.</p><button class="btn">Apri</button></div><div class="card"><h3>SISGAP</h3><p class="mini">Operazioni che restano in capo all'Ente.</p><button class="btn">Apri</button></div><div class="card"><h3>Verifica elaborati</h3><p class="mini">Come accettare, chiedere chiarimenti o integrazioni.</p><button class="btn">Apri</button></div></div>`,

'wb-home':()=>hero('Coda di lavoro','Il Workbench espone solo il lavoro interno: presa in carico, responsabilità, scadenze e dipendenze.','workbench')+
kpis([['Da prendere in carico','4','entro 2 giorni'],['In lavorazione','7','2 prioritarie'],['Da validare','3','PI-021 inclusa'],['Scadenze oggi','2','nessuna scaduta']])+
cardTable(['Pratica','Richiesta','Scadenza','Responsabile','Stato'],[['PI-021','Bozza determinazione','02/10/2026','L. Rossi',status('Da validare','warn')],['PI-023','Parere affidamento','03/10/2026','A. Verdi',status('In lavorazione','blue')],['PI-025','Accesso agli atti','05/10/2026','Da assegnare',status('Nuovo','violet')]]),
'wb-case':()=>hero('Pratica PI-021','La stessa pratica vista dal Comune, ma con strumenti interni di produzione, fonti e versionamento.')+
`<div class="grid two"><div class="card" data-guide="case"><div class="section-title"><h2>Contesto</h2>${status('Da validare','warn')}</div><p><b>Richiesta:</b> schema di determinazione per manutenzione straordinaria.</p><p class="mini">Categoria O6 · €450 · scadenza 02/10/2026 · Autore: Luca Rossi · Validatore: Anna Verdi</p><div class="alert">L'elaborato è istruttorio: l'adozione dell'atto resta in capo all'Ente.</div></div><div class="card"><h2>Versioni</h2><div class="list"><div class="list-item">v1 · prima bozza ${status('superata','blue')}</div><div class="list-item">v2 · revisione autore ${status('corrente','warn')}</div></div><button class="btn primary" style="margin-top:12px" onclick="showView('wb-validate')">Vai alla validazione</button></div></div>`,
'wb-sources':()=>hero('Fonti & versioni','Le fonti utilizzate sono collegate alla pratica; una fonte non verificata non viene trattata come evidenza definitiva.')+
cardTable(['Fonte','Tipo','Data','Uso','Stato'],[['D.Lgs. 36/2023','Normativa','vigente','Presupposti affidamento',status('Verificata','ok')],['Capitolato Ente','Documento pratica','29/09/2026','Oggetto e prestazioni',status('Acquisito','ok')],['Nota interna','Appunto','30/09/2026','Punto da chiarire',status('Da verificare','warn')]]),
'wb-validate':()=>hero('Validazione indipendente','Il validatore controlla coerenza, fonti, completezza e confini della prestazione prima della consegna.')+
`<div class="grid two"><div class="card" data-guide="check"><h2>Checklist</h2><div class="list"><div class="list-item">Oggetto coerente con ordinativo ${status('OK','ok')}</div><div class="list-item">Riferimenti normativi verificati ${status('OK','ok')}</div><div class="list-item">Dati dell'Ente separati da assunzioni ${status('OK','ok')}</div><div class="list-item">Campo importo quadro economico ${status('manca','warn')}</div></div></div><div class="card"><h2>Decisione del validatore</h2><p class="mini">Il file non viene consegnato finché le criticità bloccanti non sono chiuse.</p><div class="decision"><button class="btn primary" onclick="toast('Validazione completata: simulazione')">Valida</button><button class="btn" onclick="toast('Restituito all’autore')">Richiedi modifica</button></div></div></div>`,
'wb-delivery':()=>hero('Consegne','Il pacchetto finale rende riconoscibili versione, autore, validatore e pratica di origine.')+cardTable(['Pratica','Elaborato','Versione','Validato','Esito'],[['PI-021','Bozza determinazione.docx','v2','In corso',status('Non consegnabile','warn')],['PI-024','Nota sintetica.pdf','v1','30/09/2026',status('Consegnato','ok')]]),

'ctl-home':()=>hero('Quadro di controllo','Control governa contratto, plafond, SLA, ruoli e audit. Non modifica il contenuto professionale degli elaborati.')+
kpis([['Valore massimo','€ 139k','accordo complessivo'],['Plafond A','€ 7.350','residuo annuo'],['SLA rispettati','96%','ultimi 30 gg'],['Eventi audit','184','mese corrente']])+
`<div class="grid two"><div class="card" data-guide="contract"><h2>Contratto attivo · Comune di Valle Verde</h2><p class="mini">Servizio A · canone €12.000/anno · durata 24 mesi</p><div class="progress"><span style="width:61%"></span></div><p class="mini">61% del plafond annuo utilizzato</p><button class="btn" onclick="showView('ctl-contracts')">Apri contatore</button></div><div class="card"><h2>Segnalazioni</h2><div class="list"><div class="list-item">PI-021 · validazione vicina a scadenza ${status('attenzione','warn')}</div><div class="list-item">Accessi anomali ${status('nessuno','ok')}</div><div class="list-item">Backup ultimo test ${status('superato','ok')}</div></div></div></div>`,
'ctl-contracts':()=>hero('Contratti & plafond','Ogni impegno è riconciliabile con il contratto e con il contatore. Il prototipo mostra la logica, non effettua contabilità reale.')+
cardTable(['Movimento','Servizio','Importo','Plafond residuo','Stato'],[['Canone annuale','A','€12.000','€12.000',status('Imputato','ok')],['PI-021 · O6','A','€450','€7.350',status('Consumato','blue')],['Progetto B-003','B','€6.500','€121.200 max',status('Imputato','ok')]]),
'ctl-users':()=>hero('Utenti & ruoli','Le autorizzazioni sono separate per Ente e ruolo; nel prodotto reale devono essere applicate lato server.')+
cardTable(['Utente','Organizzazione','Ruolo','Accesso'],[['Maria Bianchi','Comune Valle Verde','Referente Ente','Desk'],['Luca Rossi','PRIMA','Autore','Workbench'],['Anna Verdi','PRIMA','Validatore','Workbench'],['Amministratore','PRIMA','Control admin','Control']]),
'ctl-sla':()=>hero('SLA & qualità','Le scadenze decorrono dalla registrazione valida dell’ordinativo. Le cause di sospensione devono essere tracciate.')+
cardTable(['Pratica','Presa in carico','Termine','Tempo residuo','Esito'],[['PI-021','29/09 10:20','02/10','18 ore',status('In tempo','ok')],['PI-023','30/09 09:10','03/10','42 ore',status('In tempo','ok')],['PI-019','24/09 14:10','29/09','—',status('Chiuso','blue')]]),
'ctl-audit':()=>hero('Audit & sicurezza','Ogni evento significativo registra attore, ruolo, oggetto, timestamp e motivazione, minimizzando i dati nei log.')+
cardTable(['Quando','Attore','Evento','Oggetto','Esito'],[['01/10 11:42','Anna Verdi','Apertura validazione','PI-021',status('OK','ok')],['01/10 10:15','Luca Rossi','Nuova versione','DOC-211',status('OK','ok')],['30/09 18:01','Maria Bianchi','Upload allegato','PI-023',status('OK','ok')]]),
'ctl-config':()=>hero('Configurazione','Parametri contrattuali, ruoli e integrazioni sono separati dal contenuto delle pratiche.')+`<div class="grid three"><div class="card"><h3>Tariffe</h3><p class="mini">O1–O16 e termini</p><button class="btn">Apri</button></div><div class="card"><h3>Integrazioni</h3><p class="mini">Identità, protocollo, PEC</p><button class="btn">Apri</button></div><div class="card"><h3>Retention</h3><p class="mini">Regole documentali e log</p><button class="btn">Apri</button></div></div>`,

'pat-home':()=>hero('Portafoglio territoriale','Asset, domanda e decisioni: non un inventario statico, ma una pipeline che evidenzia cosa manca per trasformare una risorsa in progetto.')+
kpis([['Asset censiti','74','52 con fonte primaria'],['Opportunity candidate','13','5 oltre G3'],['Comuni collegati','6','2 progetti in rete'],['Decisioni richieste','7','3 entro 30 giorni']])+
`<div class="grid two"><div class="card" data-guide="opps"><h2>Opportunità prioritarie</h2><div class="list"><div class="list-item"><div><b>Ex scuola → alloggi sanitari</b><div class="mini">Stima CAPEX</div></div>${status('G4','ok')}</div><div class="list-item"><div><b>Boschi + segheria + rete calore</b><div class="mini">Verifica domanda termica</div></div>${status('G3','warn')}</div><div class="list-item"><div><b>Tetto municipio → autoconsumo</b><div class="mini">Verifica connessione</div></div>${status('G2','blue')}</div></div></div><div class="card"><h2>Prossime decisioni</h2><p class="mini">La piattaforma rende esplicito chi deve decidere e quale evidenza manca.</p><button class="btn primary" onclick="showView('pat-dossier')">Apri dossier OPP-006</button></div></div>`,
'pat-map':()=>hero('Mappa asset e domanda','La distanza genera candidati; non dimostra da sola fattibilità o convenienza.')+`<div class="map" data-guide="map"><div class="road"></div><div class="river"></div><div class="pin" style="left:22%;top:34%" onclick="showView('pat-asset')"></div><div class="pin" style="left:58%;top:50%"></div><div class="pin demand" style="left:69%;top:29%" onclick="showView('pat-demand')"></div><div class="pin demand" style="left:42%;top:67%"></div><div class="map-legend">● Asset &nbsp; <span style="color:#b78b31">●</span> Domanda · clicca un punto</div></div>`,
'pat-asset':()=>hero('Asset A-024 · Ex scuola “San Michele”','La scheda distingue dato, fonte e stato di verifica.')+`<div class="grid two"><div class="card" data-guide="asset"><div class="form-grid"><div class="field"><label>Tipologia</label><select><option>Edificio pubblico dismesso</option></select></div><div class="field"><label>Ente titolare</label><input value="Comune di Valle Verde"></div><div class="field"><label>Superficie (m²)</label><input value="1.240"></div><div class="field"><label>Disponibilità giuridica</label><select><option>Da verificare</option></select></div><div class="field"><label>Fonte primaria</label><input value="Inventario patrimonio 2025"></div><div class="field"><label>Costi attuali</label><input value="€18.400/anno"></div></div></div><div class="card"><h2>Maturità</h2><div class="gatebar"><div class="gate done">G0<br>Censito</div><div class="gate current">G1<br>Disponibilità</div><div class="gate">G2</div><div class="gate">G3</div><div class="gate">G4</div><div class="gate">G5</div><div class="gate">G6</div></div><div class="alert">Blocco: titolo e diritti di terzi da verificare.</div></div></div>`,
'pat-demand':()=>hero('Domanda e fabbisogni','Ogni record deve avere soggetto, quantità, validità e fonte.')+cardTable(['ID','Soggetto','Bisogno','Quantità','Stato'],[['D-018','Azienda sanitaria','Alloggi temporanei','12–18 posti',status('Verificata','ok')],['D-021','Consorzio agricolo','Acqua irrigua','70.000 m³/anno',status('Da confermare','warn')],['D-026','Operatore forestale','Deposito/essiccazione','800 m²',status('Manifestazione','blue')]]),
'pat-match':()=>hero('Opportunity Match','Il matching è spiegabile: mostra condizioni superate e blocchi, senza assegnare automaticamente convenienza.')+`<div class="grid two"><div class="card match" data-guide="match"><h3>Ex scuola ↔ D-018 Alloggi</h3><div class="reason">Superficie compatibile; distanza 12 km; domanda attiva. <b>Blocco:</b> disponibilità giuridica non verificata.</div><button class="btn primary" style="margin-top:12px" onclick="showView('pat-dossier')">Apri dossier</button></div><div class="card match"><h3>Bosco ↔ D-026 Deposito</h3><div class="reason">2.900 ha forestali; operatore a 18 km. Manca piano di gestione aggiornato.</div></div></div>`,
'pat-dossier':()=>hero('Opportunity dossier · OPP-006','L’opportunità avanza solo quando supera verifiche identificabili.')+`<div class="card" data-guide="gates"><div class="gatebar"><div class="gate done">G0<br>Censito</div><div class="gate done">G1<br>Disponibile</div><div class="gate done">G2<br>Plausibile</div><div class="gate done">G3<br>Domanda</div><div class="gate current">G4<br>Economia</div><div class="gate">G5<br>Percorso</div><div class="gate">G6<br>Sviluppo</div></div></div><div class="grid two" style="margin-top:16px"><div class="card"><h2>Alternative</h2><p>0 · Stato attuale — costi €18,4k/anno</p><p>1 · Recupero minimo — CAPEX €220–310k</p><p>2 · Alloggi temporanei — CAPEX €520–690k</p></div><div class="card"><h2>Decisione</h2><p class="mini">Autorizzare pre-fattibilità tecnica/economica.</p><button class="btn primary" data-toast="Pre-fattibilità avviata: simulazione">Approfondisci</button></div></div>`,
'pat-network':()=>hero('Progetti in rete','Combina risorse complementari di più Comuni, senza aggregare beni solo per aumentare la dimensione.')+`<div class="grid three"><div class="card"><h3>Filiera bosco–legno–calore</h3><p class="mini">3 Comuni · 4 asset · 2 domande</p><div class="progress"><span style="width:52%"></span></div></div><div class="card"><h3>Alloggi lavoratori</h3><p class="mini">4 Comuni · 11 immobili · 3 imprese</p><div class="progress"><span style="width:71%"></span></div></div><div class="card"><h3>Acqua–agricoltura</h3><p class="mini">2 Comuni · depuratore + 340 ha</p><div class="progress"><span style="width:38%"></span></div></div></div>`,
'pat-quality':()=>hero('Data quality','L’assenza di un dato deve diventare una verifica aperta, non un valore inventato.')+kpis([['Core completi','82%',''],['Fonti scadute','9',''],['Campi bloccanti','14',''],['Verifiche aperte','21','']])+cardTable(['Asset','Problema','Priorità'],[['A-024','Titolarità non verificata',status('Bloccante','bad')],['A-037','Consumi energetici 2023',status('Aggiornare','warn')],['A-052','Coordinate mancanti',status('Utile','blue')]]),
'pat-admin':()=>hero('Admin e ruoli','Il prototipo mostra chi può vedere, modificare e validare; nel prodotto reale i permessi saranno server-side.')+cardTable(['Utente','Ente','Ruolo','Permessi'],[['Maria Bianchi','Valle Verde','Referente Ente','Asset, domanda, decisioni'],['Luca Rossi','PRIMA','Analista','Analisi, matching, dossier'],['Anna Verdi','PRIMA','Validatore','Gate, validazioni, export']]),
'pat-integrations':()=>hero('Integrazioni','Patrimonio & Progetti è ora parte dell’Ecosistema: mantiene un dominio funzionale distinto, ma con navigazione e identificativi comuni.')+`<div class="grid three"><div class="card"><h3>Import CSV</h3><p class="mini">Asset e anagrafiche</p><button class="btn">Carica</button></div><div class="card"><h3>Open data / API</h3><p class="mini">Fonti pubbliche selezionate</p><button class="btn">Configura</button></div><div class="card"><h3>Prima Desk</h3><p class="mini">Collegamento Opportunity ID → pratica</p><button class="btn" onclick="enterEnv('desk')">Apri Desk</button></div></div>`
};
const GUIDES={
'desk-home':[['hero','Il punto di vista del Comune','Il Desk mostra soltanto ciò che serve al referente: richieste, stato, consegne e prossime azioni.'],['case','Una pratica, più ambienti','PI-021 è visibile anche nel Workbench e in Control, ma con strumenti diversi in base al ruolo.'],['next','Prossimo passo','Il referente non deve interpretare una dashboard: il sistema evidenzia l’azione richiesta e la relativa scadenza.']],
'desk-new':[['form','Ordinativo guidato','La maschera raccoglie gli elementi necessari per classificare la prestazione, controllare la capienza e far partire correttamente i termini.']],
'wb-home':[['hero','Coda interna','Il Workbench separa il lavoro professionale dalla vista del Comune. Qui compaiono assegnazioni, scadenze e stati interni.']],
'wb-case':[['case','Contesto controllato','Autore e validatore sono distinti. L’elaborato resta istruttorio e non assume efficacia esterna.']],
'wb-validate':[['check','Validazione','La consegna è bloccata finché le criticità rilevanti non sono chiuse o motivate.']],
'ctl-home':[['hero','Governo del servizio','Control non è un altro gestionale operativo: governa contratto, consumo, qualità e sicurezza.'],['contract','Contatore','Il consumo della pratica PI-021 è riconciliato con il plafond e con il contratto.']],
'pat-home':[['hero','Un quarto ambiente distinto','Patrimonio & Progetti non è una funzione del Desk: è un ambiente di sviluppo opportunità collegato all’ecosistema.'],['opps','Pipeline','I Gate indicano verifiche superate, non un punteggio automatico.']],
'pat-map':[['map','Relazioni territoriali','La mappa aiuta a trovare connessioni tra asset e domanda, senza confondere prossimità con fattibilità.']],
'pat-asset':[['asset','Scheda asset','Ogni informazione importante deve avere fonte e stato di verifica.']],
'pat-match':[['match','Matching spiegabile','Il sistema spiega perché un match è candidato e quale blocco ne impedisce l’avanzamento.']],
'pat-dossier':[['gates','Gate di maturità','Dal censimento allo sviluppo: il passaggio avviene solo con evidenze verificabili.']]
};
function guideSteps(){return GUIDES[currentView]||[['','Come usare questa schermata','Esplora i dati dimostrativi e usa i pulsanti disponibili. La guida non sostituisce una procedura formale.']]}
function openGuide(){q('#guidePanel').classList.add('open');guideIndex=0;renderGuide()}function closeGuide(){q('#guidePanel').classList.remove('open');qa('.guide-highlight').forEach(x=>x.classList.remove('guide-highlight'))}
function renderGuide(){qa('.guide-highlight').forEach(x=>x.classList.remove('guide-highlight'));const a=guideSteps();guideIndex=Math.max(0,Math.min(guideIndex,a.length-1));const [target,t,txt]=a[guideIndex];q('#guideStep').textContent=`Passaggio ${guideIndex+1} di ${a.length} · ${title()}`;q('#guideTitle').textContent=t;q('#guideText').textContent=txt;q('#guidePrev').disabled=guideIndex===0;q('#guideNext').textContent=guideIndex===a.length-1?'Fine':'Avanti →';if(target){const el=q(`[data-guide="${target}"]`);if(el){el.classList.add('guide-highlight');el.scrollIntoView({behavior:'smooth',block:'center'})}}}
q('#guideBtn').onclick=openGuide;q('#guideClose').onclick=closeGuide;q('#guidePrev').onclick=()=>{if(guideIndex>0){guideIndex--;renderGuide()}};q('#guideNext').onclick=()=>{const a=guideSteps();if(guideIndex<a.length-1){guideIndex++;renderGuide()}else closeGuide()};
function toast(t){const x=q('#toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',1800)}
function openModal(title,body,cb){q('#modalTitle').textContent=title;q('#modalBody').innerHTML=body;q('#genericModal').classList.add('open');modalCallback=cb||null}
function closeModal(){q('#genericModal').classList.remove('open');modalCallback=null}
function modalConfirm(){if(modalCallback)modalCallback();closeModal();toast('Operazione registrata nel prototipo')}
function openCaseModal(){openModal('Pratica PI-021','<p><b>Oggetto:</b> schema di determinazione — manutenzione straordinaria.</p><p><b>Stato:</b> validazione in corso.</p><p><b>Prossimo passo:</b> consegna al referente dell’Ente dopo validazione.</p>')}
function openAssetModal(){openModal('Nuovo asset','<div class="form-grid"><div class="field"><label>Denominazione</label><input placeholder="Es. Ex scuola via Roma"></div><div class="field"><label>Tipologia</label><select><option>Edificio</option><option>Terreno</option><option>Bosco</option><option>Impianto</option></select></div><div class="field"><label>Comune</label><input placeholder="Comune"></div><div class="field"><label>Fonte</label><input placeholder="Inventario / atto / visura"></div></div>')}
function startDemo(){demoStep=0;enterEnv('desk','desk-home');setTimeout(()=>openModal('Percorso dimostrativo','<p>Il percorso segue una stessa pratica dal Comune al Workbench e a Control, quindi mostra come Patrimonio & Progetti si integra come quarto ambiente distinto.</p><p><b>1.</b> Desk: il Comune vede PI-021.<br><b>2.</b> Workbench: PRIMA la lavora.<br><b>3.</b> Control: contratto e audit.<br><b>4.</b> Patrimonio & Progetti: opportunità territoriali.</p>',()=>demoNext()),250)}
function demoNext(){demoStep++;if(demoStep===1){enterEnv('workbench','wb-case');toast('2/4 · Workbench: lavorazione PI-021')}else if(demoStep===2){enterEnv('control','ctl-home');toast('3/4 · Control: governo e contatore')}else if(demoStep===3){enterEnv('patrimonio','pat-home');toast('4/4 · Patrimonio & Progetti')}else toast('Percorso completato')}
window.enterEnv=enterEnv;window.showView=showView;window.goHome=goHome;window.startDemo=startDemo;window.toast=toast;window.openCaseModal=openCaseModal;window.openAssetModal=openAssetModal;window.closeModal=closeModal;window.modalConfirm=modalConfirm;
