const titles={portfolio:'P01 · Portfolio',map:'P02 · Mappa',asset:'P03 · Asset',demand:'P04 · Domanda / Fabbisogni',match:'P05 · Opportunity Match',dossier:'P06 · Opportunity dossier',network:'P07 · Progetti in rete',quality:'P08 · Data quality',admin:'P09 · Admin / Ruoli',integrations:'P10 · Integrazioni'};
const guides={
portfolio:[['hero','Cosa stai guardando','Questa è la vista di portafoglio. Non serve a “fare bella figura”: deve dire subito quali risorse esistono, quali opportunità stanno maturando e quali decisioni bloccano il lavoro.'],['kpis','Indicatori essenziali','I KPI mostrano quantità operative: asset censiti, opportunità candidate, Comuni collegati e decisioni richieste. Nel prodotto reale ogni numero deve essere cliccabile e riconciliabile con i record sottostanti.'],['pipeline','Pipeline delle opportunità','Ogni opportunità ha un Gate. Il Gate non è un punteggio: indica quale verifica minima è stata effettivamente superata.'],['next','Prossime decisioni','La piattaforma deve sempre suggerire il prossimo passo concreto, chi deve compierlo e quale evidenza manca.']],
map:[['map','Mappa territoriale','Visualizza insieme asset e domanda. La distanza aiuta a generare candidati, ma non dimostra fattibilità: i match devono poi superare regole e verifiche.']],
asset:[['assetCore','Scheda dell’asset','Qui si raccolgono dati minimi con fonte e stato di verifica. Il prototipo evita di chiedere informazioni che potrebbero essere importate da fonti esistenti.'],['assetStatus','Gate di maturità','G0 significa solo che sappiamo che il bene esiste. Per passare a G1 dobbiamo verificare che il Comune possa legittimamente disporne o attivare il percorso.']],
demand:[['demandTable','Banca della domanda','La piattaforma non deve raccogliere solo beni: deve registrare chi cerca cosa, in quale quantità, con quale scadenza e con quale livello di verifica.']],
match:[['matchReason','Perché il match esiste','Il matching iniziale è rule-based e spiegabile. Il sistema mostra condizioni superate e blocchi. Non assegna automaticamente convenienza o legittimità.'],['rules','Regole verificabili','Le regole devono essere leggibili e modificabili: distanza, soglie, disponibilità, validità della domanda, documenti necessari.']],
dossier:[['gates','Dossier e Gate','Il dossier accompagna l’opportunità da G0 a G6. Qui l’opportunità ha superato la domanda (G3) e deve dimostrare ordine di grandezza economico e alternative (G4).']],
network:[['','Progetti in rete','Questa vista collega risorse complementari di più Comuni: non aggrega per forza beni simili, ma può combinare asset, domanda, infrastrutture e operatori.']],
quality:[['','Qualità dei dati','Campi mancanti e fonti scadute devono diventare una coda operativa. L’assenza di un dato può essere esplicita: non va nascosta con valori inventati.']],
admin:[['','Ruoli e responsabilità','Nel prodotto reale i permessi devono essere applicati lato server con segregazione dei ruoli. Il prototipo serve a definire chi può vedere, modificare, validare e decidere.']],
integrations:[['','Autonoma oggi, integrabile domani','La piattaforma può nascere separata da PRIMA DESK, purché usi identificativi stabili, API e regole di export/import fin dall’inizio.']]
};
let current='portfolio',gIndex=0;
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));current=id;document.getElementById('crumb').textContent=titles[id];gIndex=0;if(document.getElementById('guidePanel').classList.contains('open'))renderGuide();window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
function clearHighlight(){document.querySelectorAll('.guide-highlight').forEach(e=>e.classList.remove('guide-highlight'));}
function renderGuide(){clearHighlight();const arr=guides[current]||[];if(!arr.length)return;gIndex=Math.max(0,Math.min(gIndex,arr.length-1));const [target,title,text]=arr[gIndex];document.getElementById('guideStep').textContent=`Passaggio ${gIndex+1} di ${arr.length} · ${titles[current]}`;document.getElementById('guideTitle').textContent=title;document.getElementById('guideText').textContent=text;document.getElementById('guidePrev').disabled=gIndex===0;document.getElementById('guideNext').textContent=gIndex===arr.length-1?'Fine':'Avanti →';if(target){const el=document.querySelector(`#${current} [data-guide="${target}"]`);if(el){el.classList.add('guide-highlight');el.scrollIntoView({behavior:'smooth',block:'center'});}}}
document.getElementById('guideBtn').onclick=()=>{document.getElementById('guidePanel').classList.toggle('open');gIndex=0;renderGuide();};
document.getElementById('guideClose').onclick=()=>{document.getElementById('guidePanel').classList.remove('open');clearHighlight();};
document.getElementById('guidePrev').onclick=()=>{if(gIndex>0){gIndex--;renderGuide();}};
document.getElementById('guideNext').onclick=()=>{const arr=guides[current]||[];if(gIndex<arr.length-1){gIndex++;renderGuide();}else{document.getElementById('guidePanel').classList.remove('open');clearHighlight();}};
function openModal(id){document.getElementById(id).classList.add('open')}function closeModal(id){document.getElementById(id).classList.remove('open')}function why(t){document.getElementById('whyText').textContent=t;openModal('whyModal')}function saveToast(t){const el=document.getElementById('toast');el.textContent=t;el.style.display='block';setTimeout(()=>el.style.display='none',1800)}